source 'https://github.com/CocoaPods/Specs.git'

target 'JHGlowView', :exclusive => true do
  pod "JHGlowView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "JHGlowView", :path => "../"

  
end
